### ISSUE TITLE
Error when using "

### ISSUE THREAD

**Issue by base698** [paradigm/TextObjectify#2]
Getting this error:
Error detected while processing function TextObjectify..<SNR>19_SearchSameLine..<SNR>19_CursorInRange:line   12:InterruptedI

When doing something with a " text object.

Example was:
"

Test
"

Thanks!

**Comment by base698** [comment]
I interrupted it.  It was in an infinite loop before.

**Comment by paradigm** [comment]
Yep, if the cursor is on the second line of 

```
"

Test
"
```

It seems to get into an infinite loop.  This also happens with the single-quote and backtick objects.  I'll see if I can figure it out and fix it - thanks for notifying me.

**Comment by paradigm** [comment]
Fixed in 4cc08d596b74f97e8a63e2366a65230ab82eb3a1
