### ISSUE TITLE
<CR> object broken on EOF

### ISSUE THREAD

**Issue by dag** [paradigm/TextObjectify#5]
Put the cursor at the very last character in a buffer and type any of `vi<CR>` or `va<CR>` and nothing happens.  At least not for me; I haven't tested it in a clean Vim environment.

**Comment by paradigm** [comment]
I'm seeing that as well.  I'll look into it.

**Comment by dag** [comment]
Meant to say "very last character", not just line.  Edited.

**Comment by paradigm** [comment]
fixed in dacfa7b6c6eef75397eb36e9a1d0c8e3f6f8de42
